name: asrt_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0=cpu_0
  - aiohttp=3.8.4=py310h90acd4f_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - aom=3.5.0=hf0c8a7f_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h90acd4f_3
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - autoreject=0.4.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.2=pyha770c72_0
  - blas=1.1=openblas
  - bleach=6.0.0=pyhd8ed1ab_0
  - blosc=1.21.2=hebb52c4_0
  - brotli=1.0.9=hb7f2c08_8
  - brotli-bin=1.0.9=hb7f2c08_8
  - brotlipy=0.7.0=py310h90acd4f_1005
  - brunsli=0.1=h046ec9c_0
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.18.1=h0d85af4_0
  - c-blosc2=2.7.1=had5f71b_0
  - ca-certificates=2025.2.25=hecd8cb5_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=5.3.0=pyhd8ed1ab_0
  - certifi=2025.1.31=py310hecd8cb5_0
  - cffi=1.15.1=py310ha78151a_3
  - cfitsio=4.2.0=hd56cc12_0
  - charls=2.4.1=hf0c8a7f_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - colorspacious=1.1.2=pyh24bf2e0_0
  - comm=0.1.2=pyhd8ed1ab_0
  - contourpy=1.0.7=py310ha23aa8a_0
  - cryptography=39.0.2=py310hdd0c95c_0
  - curl=7.86.0=h581aaea_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py310h90acd4f_1
  - dal=2023.2.1=h694c41f_1034
  - darkdetect=0.8.0=pyhd8ed1ab_0
  - dask-core=2023.3.1=pyhd8ed1ab_0
  - dav1d=1.0.0=hac89ed1_1
  - debugpy=1.6.6=py310h7a76584_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - deprecated=1.2.13=pyh6c4a22f_0
  - dipy=1.6.0=py310h936d966_0
  - double-conversion=3.2.0=hf0c8a7f_1
  - edflib-python=1.0.6=pyhd8ed1ab_0
  - eeglabio=0.0.2.post3=pyhd8ed1ab_0
  - eigen=3.4.0=h940c156_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hf0c8a7f_0
  - ffmpeg=5.1.2=gpl_h8b4fe81_106
  - flit-core=3.8.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h5bb23bf_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.39.0=py310h90acd4f_0
  - freetype=2.12.1=h3f81eb7_1
  - frozenlist=1.3.3=py310h90acd4f_0
  - fsspec=2023.3.0=pyhd8ed1ab_1
  - future=0.18.3=pyhd8ed1ab_0
  - gettext=0.21.1=h8a4c099_0
  - giflib=5.2.1=hb7f2c08_3
  - gl2ps=1.4.2=h4cff582_0
  - glew=2.1.0=h046ec9c_2
  - glib=2.74.1=hbc0c0cd_1
  - glib-tools=2.74.1=hbc0c0cd_1
  - gmp=6.2.1=h2e338ed_0
  - gnutls=3.7.8=h207c4f0_0
  - google-auth=2.16.3=pyh1a96a4e_0
  - google-colab=1.0.0=pyh44b312d_0
  - gst-plugins-base=1.21.3=h37e1711_1
  - gstreamer=1.21.3=h1d18e73_1
  - h5io=0.1.7=pyh8a188c0_0
  - h5py=3.8.0=nompi_py310h5555e59_100
  - hdf4=4.2.15=h7aa5921_5
  - hdf5=1.12.2=nompi_h1f71328_100
  - icu=70.1=h96cf925_0
  - idna=3.4=pyhd8ed1ab_0
  - imagecodecs=2023.1.23=py310h9517954_0
  - imageio=2.26.0=pyh24c5eb1_0
  - imageio-ffmpeg=0.4.8=pyhd8ed1ab_0
  - importlib-metadata=6.0.0=pyha770c72_0
  - importlib_metadata=6.0.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - ipycanvas=0.13.1=pyhd8ed1ab_0
  - ipyevents=2.0.1=pyhd8ed1ab_0
  - ipykernel=6.21.2=pyh736e0ef_0
  - ipython=8.15.0=py310hecd8cb5_0
  - ipython_genutils=0.2.0=py_1
  - ipyvtklink=0.2.2=pyhd8ed1ab_0
  - ipywidgets=8.0.4=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=hb7f2c08_3
  - jpype1=1.5.2=py310h1962661_1
  - jsoncpp=1.9.5=h940c156_1
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter=1.0.0=py310h2ec42d9_8
  - jupyter_client=8.0.3=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.2.0=py310h2ec42d9_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.4.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.5=pyhd8ed1ab_0
  - jxrlib=1.1=h35c211d_2
  - kiwisolver=1.4.4=py310ha23aa8a_1
  - krb5=1.19.3=hb98e516_0
  - lame=3.100=hb7f2c08_1003
  - lcms2=2.15=h29502cd_0
  - lerc=4.0.0=hb486fe8_0
  - libaec=1.0.6=hf0c8a7f_1
  - libavif=0.11.1=he9a59b1_0
  - libblas=3.9.0=16_osx64_openblas
  - libbrotlicommon=1.0.9=hb7f2c08_8
  - libbrotlidec=1.0.9=hb7f2c08_8
  - libbrotlienc=1.0.9=hb7f2c08_8
  - libcblas=3.9.0=16_osx64_openblas
  - libclang=15.0.7=default_h20dc2f0_1
  - libclang13=15.0.7=default_hc4b5f92_1
  - libcurl=7.86.0=h581aaea_1
  - libcxx=15.0.7=h71dddab_0
  - libdeflate=1.17=hac1461d_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=11_3_0_h97931a8_31
  - libgfortran5=12.2.0=he409387_31
  - libglib=2.74.1=h4c723e1_1
  - libiconv=1.17=hac89ed1_0
  - libidn2=2.3.4=hb7f2c08_0
  - liblapack=3.9.0=16_osx64_openblas
  - libllvm11=11.1.0=h8fb7429_5
  - libllvm15=15.0.7=h7001e86_1
  - libmatio=1.5.23=h9be9bca_1
  - libnetcdf=4.8.1=nompi_hc61b76e_106
  - libnghttp2=1.52.0=he2ab024_0
  - libogg=1.3.4=h35c211d_1
  - libopenblas=0.3.21=openmp_h429af6e_3
  - libopus=1.3.1=hc929b4f_1
  - libpng=1.6.39=ha978bb4_0
  - libpq=15.1=hb1ae2b1_1
  - libsodium=1.0.18=hbcb3906_1
  - libsqlite=3.40.0=ha978bb4_0
  - libssh2=1.10.0=h47af595_3
  - libtasn1=4.19.0=hb7f2c08_0
  - libtheora=1.1.1=h0d85af4_1005
  - libtiff=4.5.0=hee9004a_2
  - libunistring=0.9.10=h0d85af4_0
  - libvorbis=1.3.7=h046ec9c_0
  - libvpx=1.11.0=he49afe7_3
  - libwebp-base=1.3.0=hb7f2c08_0
  - libxcb=1.13=h0d85af4_1004
  - libxgboost=2.0.3=hab2016f_0
  - libxml2=2.10.3=hb9e07b5_3
  - libxslt=1.1.37=h5d22bc9_0
  - libzip=1.9.2=h6db710c_1
  - libzlib=1.2.13=hfd90126_4
  - libzopfli=1.0.3=h046ec9c_0
  - llvm-openmp=15.0.7=h61d9ccf_0
  - llvmlite=0.39.1=py310h2bfb868_1
  - locket=1.0.0=pyhd8ed1ab_0
  - loguru=0.6.0=py310h2ec42d9_2
  - lxml=4.9.2=py310h0b20c97_0
  - lz4-c=1.9.4=hf0c8a7f_0
  - markupsafe=2.1.2=py310h90acd4f_0
  - matplotlib=3.7.1=py310h2ec42d9_0
  - matplotlib-base=3.7.1=py310he725631_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mffpy=0.8.0=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - mne-qt-browser=0.4.0=py310h2ec42d9_0
  - mne-rsa=0.9=pyhd8ed1ab_0
  - mpi=1.0=mpich
  - mpich=4.1.1=hc226d05_0
  - multidict=6.0.4=py310h90acd4f_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.32=hc4b2c72_0
  - mysql-libs=8.0.32=h8658499_0
  - nbclassic=0.5.3=pyhb4ecaf3_3
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.9=pyhd8ed1ab_0
  - nbconvert-core=7.2.9=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.9=pyhd8ed1ab_0
  - nbformat=5.7.3=pyhd8ed1ab_0
  - ncurses=6.3=h96cf925_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nettle=3.8.1=h96f3785_1
  - networkx=3.0=pyhd8ed1ab_0
  - nibabel=5.0.1=pyhd8ed1ab_0
  - nilearn=0.10.0=pyhd8ed1ab_0
  - nlohmann_json=3.11.2=hbbd2c75_0
  - notebook=6.5.3=pyha770c72_0
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - nspr=4.35=hea0b92c_0
  - nss=3.89=h78b00b3_0
  - numba=0.56.4=py310h62db5c2_0
  - numexpr=2.8.3=py310hecf8f37_1
  - numpy=1.23.5=py310h1b7c290_0
  - openblas=0.3.21=openmp_hbefa662_3
  - openh264=2.3.1=hf0c8a7f_2
  - openjdk=21.0.6=h2761308_0
  - openjpeg=2.5.0=h13ac156_2
  - openmeeg=2.5.5=py310he9bac87_2
  - openssl=3.0.16=h184c1cd_0
  - p11-kit=0.24.1=h65f8906_0
  - packaging=23.0=pyhd8ed1ab_0
  - pandas=1.5.3=py310hecf8f37_0
  - pandoc=3.1.1=h9d075a6_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.3.0=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.40=h1c4e4bc_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py310h306a057_1
  - pip=23.0.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - ply=3.11=py_1
  - pooch=1.7.0=pyhd8ed1ab_0
  - portpicker=1.5.2=pyhd8ed1ab_0
  - proj=9.1.1=hf909084_1
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.4=py310h90acd4f_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pugixml=1.11.4=he49afe7_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py-xgboost=2.0.3=py310hecd8cb5_0
  - pyasn1=0.4.8=py_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pymatreader=0.0.30=pyhd8ed1ab_0
  - pyobjc-core=9.0=py310h4f19300_0
  - pyobjc-framework-cocoa=9.0=py310h4f19300_0
  - pyopengl=3.1.6=pyhd8ed1ab_1
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py310hdd03f62_3
  - pyqt5-sip=12.11.0=py310h415000c_3
  - pyqtgraph=0.13.2=pyhd8ed1ab_0
  - pyrsistent=0.19.3=py310h90acd4f_0
  - pysocks=1.7.1=pyha2e5f31_6
  - pytables=3.7.0=py310h90ba602_3
  - python=3.10.9=he7542f4_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-picard=0.7=pyh8a188c0_0
  - python_abi=3.10=3_cp310
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyvista=0.38.4=pyhd8ed1ab_0
  - pyvistaqt=0.9.1=pyhd8ed1ab_0
  - pywavelets=1.4.1=py310h936d966_0
  - pyyaml=6.0=py310h90acd4f_5
  - pyzmq=25.0.1=py310hf615a82_0
  - qdarkstyle=3.1=pyhd8ed1ab_0
  - qt-main=5.15.6=h0916ed4_4
  - qtconsole=5.4.1=pyhd8ed1ab_0
  - qtconsole-base=5.4.1=pyha770c72_0
  - qtpy=2.3.0=pyhd8ed1ab_0
  - readline=8.1.2=h3899abd_0
  - requests=2.28.2=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rsa=4.9=pyhd8ed1ab_0
  - rsatoolbox=0.1.4=py310hb372a2b_0
  - scikit-image=0.19.3=py310hecf8f37_2
  - scikit-learn=1.2.2=py310hcebe997_0
  - scikit-learn-intelex=2023.2.1=py310h2ec42d9_0
  - scipy=1.11.4=py310ha516a68_0
  - scooby=0.7.1=pyhd8ed1ab_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=67.6.0=pyhd8ed1ab_0
  - sip=6.7.7=py310h7a76584_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h225ccf5_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.40.0=h9ae0607_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.13.5=py310h936d966_2
  - svt-av1=1.4.1=hf0c8a7f_0
  - tbb-devel=2021.8.0=hb8565cd_0
  - terminado=0.17.1=pyhd1c38e8_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tifffile=2023.2.28=pyhd8ed1ab_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.2=py310h90acd4f_1
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - tzdata=2022g=h191b570_0
  - unicodedata2=15.0.0=py310h90acd4f_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - utfcpp=3.2.3=h694c41f_0
  - vtk=9.2.5=qt_py310hbef77d7_202
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.1=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.5=pyhd8ed1ab_0
  - wrapt=1.15.0=py310h90acd4f_0
  - wslink=1.10.1=pyhd8ed1ab_0
  - x264=1!164.3095=h775f41a_2
  - x265=3.5=hbb4e6a2_3
  - xgboost=2.0.3=py310hecd8cb5_0
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xmltodict=0.13.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h35c211d_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xz=5.2.6=h775f41a_0
  - yaml=0.2.5=h0d85af4_2
  - yarl=1.8.2=py310h90acd4f_0
  - zeromq=4.3.4=he49afe7_1
  - zfp=1.0.0=ha894c9a_3
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=hfd90126_4
  - zlib-ng=2.0.6=hac89ed1_0
  - zstd=1.5.2=hbc0c0cd_6
  - pip:
    - aiohttp-cors==0.7.0
    - annotated-types==0.6.0
    - apptools==5.3.0
    - arviz==0.21.0
    - attrs==23.2.0
    - bambi==0.15.0
    - bs4==0.0.2
    - cattrs==23.2.3
    - colorful==0.5.6
    - configobj==5.0.9
    - cons==0.4.6
    - daal==2023.2.1
    - daal4py==2023.2.1
    - dicom2nifti==2.4.8
    - distlib==0.3.8
    - ecos==2.0.14
    - envisage==7.0.3
    - etuples==0.3.9
    - exceptiongroup==1.2.1
    - filelock==3.18.0
    - formulae==0.5.4
    - freetype-py==2.4.0
    - google-api-core==2.11.0
    - google-api-python-client==2.82.0
    - google-auth-httplib2==0.1.0
    - googleapis-common-protos==1.59.0
    - grpcio==1.63.0
    - h5netcdf==1.6.1
    - hsluv==5.0.4
    - httplib2==0.22.0
    - idtxl==1.6
    - lazy-loader==0.4
    - lazypredict==0.2.12
    - levenshtein==0.20.9
    - lightgbm==4.3.0
    - linkify-it-py==2.0.3
    - littleutils==0.2.2
    - logical-unification==0.4.6
    - markdown-it-py==3.0.0
    - mayavi==4.8.2
    - mdit-py-plugins==0.4.1
    - mdurl==0.1.2
    - memray==1.12.0
    - metalcompute==0.2.5
    - minikanren==1.0.3
    - mne==1.7.1
    - mne-bids==0.16.0
    - mpmath==1.3.0
    - msgpack==1.0.8
    - multipledispatch==1.0.0
    - narwhals==1.35.0
    - neo==0.12.0
    - nose==1.3.7
    - numdifftools==0.9.41
    - numpy-stl==3.0.1
    - opencensus==0.11.4
    - opencensus-context==0.1.3
    - outdated==0.2.2
    - palettable==3.3.3
    - pandas-flavor==0.5.0
    - pingouin==0.5.3
    - pip-autoremove==0.10.0
    - platformdirs==4.2.2
    - plotly==6.0.1
    - polars==1.27.1
    - polars-lts-cpu==1.27.1
    - prettytable==3.16.0
    - protobuf==4.22.1
    - py-spy==0.3.14
    - pyasn1-modules==0.2.8
    - pydantic==2.7.1
    - pydantic-core==2.18.2
    - pydicom==2.4.1
    - pyface==8.0.0
    - pyinform==0.2.0
    - pymc==5.22.0
    - pymetal==0.5.0
    - pyopencl==2025.1
    - pysurfer==0.11.2
    - pytensor==2.30.3
    - python-gdcm==3.0.22
    - python-graphviz==0.20.3
    - python-utils==3.7.0
    - pytools==2025.1.2
    - quantities==0.15.0
    - random-user-agent==1.0.1
    - rapidfuzz==2.13.7
    - ray==2.22.0
    - requests-cache==1.2.0
    - rich==13.7.1
    - semopy==2.3.11
    - smart-open==7.0.4
    - sympy==1.13.3
    - tabulate==0.9.0
    - tbb==2021.10.0
    - textual==0.60.1
    - tqdm-joblib==0.0.4
    - traits==6.4.3
    - traitsui==8.0.0
    - typing-extensions==4.11.0
    - uc-micro-py==1.0.3
    - uritemplate==4.1.1
    - url-normalize==1.4.3
    - virtualenv==20.26.2
    - visbrain==0.4.5
    - vispy==0.14.1
    - vtkplotlib==2.1.0
    - xarray==2023.2.0
    - xarray-einstats==0.8.0
prefix: /Users/coum/opt/anaconda3/envs/asrt_analysis
